### ISSUE TITLE
Suggestion - trade BTC pairs instead of USDT

### ISSUE THREAD

**Issue by callme-sy** [Ajvar/BBB#1]
Hey this is very promising!
Unfortunately most of Big Pump Signal's pumps are in BTC pair, so i think it would be better to replace usdt with btc

**Comment by JoeSlain** [comment]
Hi @callme-sy , I've already made the change after failing a pump.
Didn't think anyone would see this, how did you find my repo ?
Also I modified the way the buy amount is calculated since I was sending the amount of BTC from the user's input instead of the number of coins required by the API.
The bot still have issues placing orders because Telgram's API applies a cooldown to requests, I'm fixing it and I don't recommend using the bot for tomorrow's pump

**Comment by callme-sy** [comment]
Nice, i found your repo by keyword search on github.
I tried this semi-auto bot : https://github.com/gobeli/pump-and-dump and also failed.
Yesterday Big Pump Signal sent the signal with a 5s delay on Telegram, maybe Discord would be better ?
I'd like to try with an instant bot like yours and if it doesn't work i'll stop trying to profit from pumps.

**Comment by JoeSlain** [comment]
I'm closing the issue, I'll look into using Discord instead of Telegram, but sometimes Discord also experiences delays due to overload.
Also I need to fix the way the bot calculates the amount to buy because Binance API doesn't accept it.
